/** Lichtgewicht register voor de request-proxy. Houdt ongeldige dynamische
    detailroutes tegen voordat de gestreamde dashboard-layout HTTP 200 verstuurt. */
export const CAREON_KPI_DETAIL_IDS = [
  "actief",
  "aanmeldingen",
  "gesloten",
  "noshow",
  "zondervervolg",
  "dossiersnc",
  "omzetverz",
  "omzetinfo",
  "omzettotaal",
  "omzetrmo",
  "outreach",
  "tevredenheid",
  "wachtlijst-intake",
  "wachtlijst-behandeling",
  "zonder-behandelaar",
  "contact30",
  "contact60",
  "crisis",
  "afspraken",
  "geannuleerd",
  "bezetting",
  "uren-beschikbaar",
  "uren-productief",
  "uren-behandel",
  "uren-indirect",
  "wachttijd",
  "ohw",
  "openstaand",
  "afgekeurd",
  "omzet-client",
  "omzet-traject",
  "declaraties90",
  "verzuim",
  "verloop",
  "vacatures",
  "opleidingen",
  "intervisie",
  "werkdruk",
  "incidenten",
  "klachten",
  "dossierkwaliteit",
  "productie-uren",
  "productiviteit",
  "wachtlijst-totaal",
  "wachtlijst-urgent",
  "dossier-compliance",
] as const;

export const CAREON_KPI_DETAIL_ID_SET: ReadonlySet<string> = new Set(CAREON_KPI_DETAIL_IDS);
