-- Careon Pulse — production hardening for assistant actions and shared state.
-- Additive migration: existing snapshots remain intact and receive a stable
-- monotonic revision in their original save order.

alter table public.careon_middelen_state
  add column if not exists revision bigint,
  add column if not exists base_revision bigint,
  add column if not exists operation_id uuid,
  add column if not exists change_source text,
  add column if not exists change_summary jsonb not null default '{}'::jsonb,
  add column if not exists actor_hash text;

with ranked as (
  select id, row_number() over (order by saved_at asc, id asc) as assigned_revision
  from public.careon_middelen_state
)
update public.careon_middelen_state as target
set revision = ranked.assigned_revision
from ranked
where target.id = ranked.id
  and target.revision is null;

alter table public.careon_middelen_state
  alter column revision set not null;

alter table public.careon_middelen_state
  drop constraint if exists careon_middelen_state_revision_positive,
  add constraint careon_middelen_state_revision_positive check (revision > 0),
  drop constraint if exists careon_middelen_state_base_revision_nonnegative,
  add constraint careon_middelen_state_base_revision_nonnegative
    check (base_revision is null or base_revision >= 0),
  drop constraint if exists careon_middelen_state_change_source_valid,
  add constraint careon_middelen_state_change_source_valid
    check (change_source is null or change_source in ('assistant', 'manual'));

create unique index if not exists careon_middelen_state_revision_uidx
  on public.careon_middelen_state (revision);

create unique index if not exists careon_middelen_state_operation_uidx
  on public.careon_middelen_state (operation_id)
  where operation_id is not null;

create table if not exists public.careon_assistant_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_id uuid not null,
  actor_hash text not null,
  event_type text not null,
  model text,
  api_mode text,
  prompt_version text,
  status_code integer,
  duration_ms integer,
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  tool_names text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  constraint careon_assistant_events_type_valid check (
    event_type in (
      'request_started',
      'request_completed',
      'request_failed',
      'request_blocked',
      'concept_applied',
      'concept_rejected',
      'sync_write',
      'sync_conflict'
    )
  ),
  constraint careon_assistant_events_duration_nonnegative
    check (duration_ms is null or duration_ms >= 0),
  constraint careon_assistant_events_tokens_nonnegative check (
    (input_tokens is null or input_tokens >= 0)
    and (output_tokens is null or output_tokens >= 0)
    and (total_tokens is null or total_tokens >= 0)
  )
);

create index if not exists careon_assistant_events_created_at_idx
  on public.careon_assistant_events (created_at desc);

create index if not exists careon_assistant_events_actor_created_idx
  on public.careon_assistant_events (actor_hash, created_at desc);

create index if not exists careon_assistant_events_request_idx
  on public.careon_assistant_events (request_id);

alter table public.careon_assistant_events enable row level security;

-- Runtime access is server-only. RLS remains enabled without client policies,
-- and table grants are explicit for current Supabase privilege semantics.
revoke all on table public.careon_middelen_state from anon, authenticated;
revoke all on table public.careon_assistant_events from anon, authenticated;
revoke all on sequence public.careon_assistant_events_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.careon_middelen_state to service_role;
grant select, insert, update, delete on table public.careon_assistant_events to service_role;
grant usage, select on sequence public.careon_assistant_events_id_seq to service_role;
