import type { KlinischeStaat, Spreker } from "../../lib/careon-scribe/types";

export interface EnglishEvidenceExample {
  name: string;
  source: string;
  field: keyof KlinischeStaat;
  expected: boolean;
  speaker?: Spreker;
  additions?: Record<string, unknown>;
  quote?: string;
}

export const ENGLISH_EVIDENCE_EXAMPLES: EnglishEvidenceExample[] = [
  {
    name: "explicit current medicine",
    source: "I take sertraline 50 mg every morning.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: "50 mg", gebruik: "huidig" },
    expected: true,
  },
  {
    name: "wrong dose not in source",
    source: "I take sertraline 50 mg every morning.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: "100 mg", gebruik: "huidig" },
    expected: false,
  },
  {
    name: "dose cannot bind to another medicine",
    source: "I take sertraline 50 mg and tramadol 100 mg every morning.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: "100 mg", gebruik: "huidig" },
    expected: false,
  },
  {
    name: "second medicine retains its adjacent dose",
    source: "I take sertraline 50 mg and tramadol 100 mg every morning.",
    field: "medicatie",
    additions: { naam: "tramadol", dosering: "100 mg", gebruik: "huidig" },
    expected: true,
  },
  {
    name: "missing dose never borrows the next medicine's dose",
    source: "I take sertraline and tramadol 100 mg every morning.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: "100 mg", gebruik: "huidig" },
    expected: false,
  },
  {
    name: "unspecified dose stays null",
    source: "I take sertraline every morning.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: null, gebruik: "huidig" },
    expected: true,
  },
  {
    name: "multiword medicine is matched as one phrase",
    source: "I take sodium valproate 500 mg every evening.",
    field: "medicatie",
    additions: { naam: "sodium valproate", dosering: "500 mg", gebruik: "huidig" },
    expected: true,
  },
  {
    name: "decimal dose is preserved",
    source: "I take lorazepam 0.5 mg every evening.",
    field: "medicatie",
    additions: { naam: "lorazepam", dosering: "0,5 mg", gebruik: "huidig" },
    expected: true,
  },
  {
    name: "dose suffix must not become a smaller dose",
    source: "I take sertraline 150 mg every morning.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: "50 mg", gebruik: "huidig" },
    expected: false,
  },
  {
    name: "stopped medicine supports stopped status",
    source: "I stopped taking sertraline last week.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: null, gebruik: "gestopt" },
    expected: true,
  },
  {
    name: "no-longer is an explicit stop",
    source: "I no longer take sertraline.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: null, gebruik: "gestopt" },
    expected: true,
  },
  {
    name: "denied current medication cannot become active",
    source: "I do not take sertraline.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: null, gebruik: "huidig" },
    expected: false,
  },
  {
    name: "negated stopping is not a stop",
    source: "I have not stopped taking sertraline.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: null, gebruik: "gestopt" },
    expected: false,
  },
  {
    name: "proposed medication stays outside current facts",
    source: "I might take sertraline next month.",
    field: "medicatie",
    additions: { naam: "sertraline", dosering: null, gebruik: "huidig" },
    expected: false,
  },
  {
    name: "clinician's personal medication is not the patient's",
    source: "I take sertraline 50 mg every morning.",
    field: "medicatie",
    speaker: "arts",
    additions: { naam: "sertraline", dosering: "50 mg", gebruik: "huidig" },
    expected: false,
  },
  {
    name: "explicit clinician report identifies the patient",
    source: "The patient takes sertraline 50 mg every morning.",
    field: "medicatie",
    speaker: "arts",
    additions: { naam: "sertraline", dosering: "50 mg", gebruik: "huidig" },
    expected: true,
  },
  {
    name: "affirmed allergy",
    source: "I am allergic to penicillin.",
    field: "allergieen",
    additions: { aard: "allergie" },
    expected: true,
  },
  {
    name: "explicit intolerance stays intolerance",
    source: "I am intolerant to lactose.",
    field: "allergieen",
    additions: { aard: "intolerantie" },
    expected: true,
  },
  {
    name: "denied allergy cannot become established",
    source: "I am not allergic to penicillin.",
    field: "allergieen",
    additions: { aard: "allergie" },
    expected: false,
  },
  {
    name: "tentative allergy cannot become established",
    source: "I may be allergic to penicillin.",
    field: "allergieen",
    additions: { aard: "allergie" },
    expected: false,
  },
  {
    name: "historical allergy remains unresolved",
    source: "I was allergic to penicillin as a child.",
    field: "allergieen",
    additions: { aard: "allergie" },
    expected: false,
  },
  {
    name: "a following denial cannot be lost",
    source: "I am allergic to penicillin. That was ruled out.",
    field: "allergieen",
    additions: { aard: "allergie" },
    expected: false,
  },
  { name: "literal current symptom", source: "I feel dizzy today.", field: "symptomen", expected: true },
  { name: "literal denial keeps its text", source: "I do not feel dizzy today.", field: "symptomen", expected: true },
  {
    name: "shortened denial is rejected",
    source: "I do not feel dizzy today.",
    quote: "I feel dizzy today.",
    field: "symptomen",
    expected: false,
  },
  {
    name: "unpunctuated English question",
    source: "Do you feel dizzy today",
    speaker: "arts",
    field: "symptomen",
    expected: false,
  },
  {
    name: "punctuated question",
    source: "Have you had any pain?",
    speaker: "arts",
    field: "symptomen",
    expected: false,
  },
  { name: "historical symptom is not current", source: "I felt dizzy last year.", field: "symptomen", expected: false },
  {
    name: "unknown role remains unknown",
    source: "I feel dizzy today.",
    speaker: "onbekend",
    field: "symptomen",
    expected: false,
  },
  {
    name: "family source is not patient evidence",
    source: "My mother feels dizzy today.",
    field: "symptomen",
    expected: false,
  },
  {
    name: "unrelated literal text is not a symptom",
    source: "I take the bus every morning.",
    field: "symptomen",
    expected: false,
  },
  {
    name: "explicit cannabis use",
    source: "I smoke cannabis every evening.",
    field: "leefstijl",
    additions: { categorie: "drugs" },
    expected: true,
  },
  {
    name: "cannabis alone is not tobacco smoking",
    source: "I smoke cannabis every evening.",
    field: "leefstijl",
    additions: { categorie: "roken" },
    expected: false,
  },
  {
    name: "explicit tobacco smoking",
    source: "I smoke five cigarettes each day.",
    field: "leefstijl",
    additions: { categorie: "roken" },
    expected: true,
  },
  {
    name: "alcohol denial remains literal",
    source: "I do not drink alcohol.",
    field: "leefstijl",
    additions: { categorie: "alcohol" },
    expected: true,
  },
  {
    name: "water drinking is not alcohol use",
    source: "I drink water each day.",
    field: "leefstijl",
    additions: { categorie: "alcohol" },
    expected: false,
  },
  {
    name: "unknown category is rejected",
    source: "I drink beer each day.",
    field: "leefstijl",
    additions: { categorie: "invented" },
    expected: false,
  },
  {
    name: "tentative option is not a plan",
    source: "We could consider sertraline at a later appointment.",
    speaker: "arts",
    field: "plan",
    expected: false,
  },
  {
    name: "tentative option is not a task",
    source: "We could consider sertraline at a later appointment.",
    speaker: "arts",
    field: "acties",
    additions: { soort: "overig", omschrijving: "We could consider sertraline at a later appointment." },
    expected: false,
  },
  {
    name: "explicit clinician commitment is a plan",
    source: "I will arrange a follow-up appointment tomorrow.",
    speaker: "arts",
    field: "plan",
    expected: true,
  },
  {
    name: "literal committed task description",
    source: "I will arrange a follow-up appointment tomorrow.",
    speaker: "arts",
    field: "acties",
    additions: { soort: "overig", omschrijving: "I will arrange a follow-up appointment tomorrow." },
    expected: true,
  },
  {
    name: "task description cannot invent instructions",
    source: "I will arrange a follow-up appointment tomorrow.",
    speaker: "arts",
    field: "acties",
    additions: { soort: "overig", omschrijving: "Admit the patient immediately." },
    expected: false,
  },
  {
    name: "conditional commitment is not an agreed plan",
    source: "I will arrange a review if you agree.",
    speaker: "arts",
    field: "plan",
    expected: false,
  },
  {
    name: "patient commitment is not a clinician task",
    source: "I will arrange a follow-up appointment tomorrow.",
    field: "acties",
    additions: { soort: "overig", omschrijving: "I will arrange a follow-up appointment tomorrow." },
    expected: false,
  },
  {
    name: "risk category cannot become an assessment",
    source: "I do not want to hurt anyone.",
    field: "psychisch",
    additions: { categorie: "veiligheid" },
    expected: false,
  },
  {
    name: "risk source is not reclassified as ordinary symptoms",
    source: "I feel anxious and hear voices.",
    field: "symptomen",
    expected: false,
  },
  {
    name: "a bus is not medication despite the word take",
    source: "I take the bus every morning.",
    field: "medicatie",
    additions: { naam: "the bus", dosering: null, gebruik: "huidig" },
    expected: false,
  },
  {
    name: "unknown medicine names remain source context",
    source: "I take inventedmed 50 mg every morning.",
    field: "medicatie",
    additions: { naam: "inventedmed", dosering: "50 mg", gebruik: "huidig" },
    expected: false,
  },
  {
    name: "tentative symptom remains source context",
    source: "I think I feel dizzy today.",
    field: "symptomen",
    expected: false,
  },
  {
    name: "a withdrawal cannot be invented on a current symptom",
    source: "I feel dizzy today.",
    field: "symptomen",
    additions: { ingetrokken: true },
    expected: false,
  },
  {
    name: "raw source length includes leading whitespace",
    source: `${" ".repeat(600)}I feel dizzy today.`,
    quote: "I feel dizzy today.",
    field: "symptomen",
    expected: false,
  },
  {
    name: "raw source length includes trailing whitespace",
    source: `I feel dizzy today.${" ".repeat(600)}`,
    quote: "I feel dizzy today.",
    field: "symptomen",
    expected: false,
  },
  {
    name: "action raw source obeys the smaller task length limit",
    source: `I will arrange a follow-up appointment tomorrow.${" ".repeat(300)}`,
    quote: "I will arrange a follow-up appointment tomorrow.",
    speaker: "arts",
    field: "acties",
    additions: { soort: "overig", omschrijving: "I will arrange a follow-up appointment tomorrow." },
    expected: false,
  },
];
